### ISSUE TITLE
Emit a redstone signal upon a transaction

### ISSUE THREAD

**Issue by gmlaxfanatic** [gmlaxfanatic/ItemExchange#14]
Implementation is up to the coder, I know this is present and used in physical shop.

**Comment by gmlaxfanatic** [comment]
Possibly make specific for trapped chests and just hook into their redstone signalling mechanism?

**Comment by shadowjay1** [comment]
Sounds like a good idea.

**Comment by shadowjay1** [comment]
Actually, after looking into vanilla code, the trapped chest solution will probably be harder than expected.
