### ISSUE TITLE
Fixes to /ies enchantment

### ISSUE THREAD

**Issue by gmlaxfanatic** [gmlaxfanatic/ItemExchange#28]
1. Not using "required" or "excluded" incorrectly gives an "Incorrect Field: enchantment" response.
2. I don't believe there is a way to remove an enchantment once you have dictated it to be required or excluded, instead you can just make it so its both required and excluded, breaking the rule block.

Perhaps the entry method should be reworked to this:

"+S5"

>  Adds an required S5 to a ruleblock without S5
> Removes excluded S5 to a ruleblock excluding S5

"-S5"

> Adds excluded S5 to a ruleblock without S5
> Removes required S5 to a ruleblock requiring S5
1. When an incorrect enchantment is entered the dialogue should include long form names of the abbreviations, otherwise people won't know what they stand for.

**Comment by shadowjay1** [comment]
Fixed by #29
