### ISSUE TITLE
Allow changes to allow unlisted enchantments

### ISSUE THREAD

**Issue by gmlaxfanatic** [gmlaxfanatic/ItemExchange#36]
Currently I don't believe there is a way to change a rule block from not allowing unlisted enchantments, there should be a command for this.

Suggested command: \ies e <All or None>

Correct me if this is implemented somewhere... I'm trying to tidy up the Readme

**Comment by shadowjay1** [comment]
Already implemented.

/ies allowenchantments
/ies denyenchantments

**Comment by gmlaxfanatic** [comment]
Awesome, thanks
