### ISSUE TITLE
Item Exchange with security notes

### ISSUE THREAD

**Issue by killyourfacego** [gmlaxfanatic/ItemExchange#51]
Myself and Oranger68 created two printing presses in order to test the exchange for items like diamond, emerald, etc with security notes for payment.  This does not seem to be functioning at all.  That is to say, whether the notes be input or output in order to sell or obtain diamond/emerald etc, item exchange is failing to recognize the transaction.

Furthermore, when attempting to toggle up or down the number of security notes for a rule block (input or output) the characters start to jump off the screen and become progressively more and more jumbled.

![3](https://f.cloud.github.com/assets/5115681/874010/a742628a-f883-11e2-90ab-07d50b2842e0.png)
![1](https://f.cloud.github.com/assets/5115681/874009/a744ce8a-f883-11e2-9f18-dc2822cbb1b0.png)
![4](https://f.cloud.github.com/assets/5115681/874012/a746a44e-f883-11e2-942c-4fee1a76ff24.png)
![2](https://f.cloud.github.com/assets/5115681/874011/a7445a86-f883-11e2-808c-714661e73bb1.png)
![6](https://f.cloud.github.com/assets/5115681/874014/a744d524-f883-11e2-90f3-1c1161924686.png)
![8](https://f.cloud.github.com/assets/5115681/874015/a750eb7a-f883-11e2-920f-2271e1ce4941.png)
![7](https://f.cloud.github.com/assets/5115681/874016/a74efa18-f883-11e2-95f7-7b941dec2053.png)
![5](https://f.cloud.github.com/assets/5115681/874013/a7450f26-f883-11e2-99cd-5a73a8c2c995.png)

These screenshots are in sequential order as I attempted to increase the input of my security notes for the rule block.

Overall I've not had any trouble with basic exchange functioning between two simple items like emerald to diamond, iron to wood, etc.  I really do like the plugin thus far and am happy that more expensive and dangerous exchanges are going to made simpler.

**Comment by gmlaxfanatic** [comment]
Thanks for the bug report! Also, fyi, its unlikely that any of the changes we make in response to your bug reports will go live until the next day. Since the server is normally only restarted in the mornings. So you'll have to wait till tomorrow to see if the fixes are implemented correctly.
