### ISSUE TITLE
Potential issue with hoppers

### ISSUE THREAD

**Issue by oranger68** [gmlaxfanatic/ItemExchange#53]
Not sure how this is going to work with the citadel groups but rule sets can be transferred into chests using hoppers.  You could transfer your own rules and take all of the items from the chest.

Again not sure how this would work with any of the citadel groups.

**Comment by gmlaxfanatic** [comment]
Can you transfer into a chest with someone else's citadel protections on it? At the moment this mod assumes that if you have access to put stuff in or take stuff out of the chest you have complete access to its contents.

This would be a major issue and one that would need to be fixed from citadel's end.

**Comment by oranger68** [comment]
If a chest is protected you can not put a hopper directly next to it, but if the hopper was placed by the owner you can throw the rules in them.  If someone had an auto potion maker or an autofeeder that inputs coal to a furnace. I think you could throw the rules in and turn the output chest into a shop.

**Comment by oranger68** [comment]
I don't think it will be in issue with what citadel has in place, but wanted to make sure it was out there

**Comment by gmlaxfanatic** [comment]
This actually should be an easy fix now that I think about it agian. Just cancel InventoryMoveItemEvent when it is from a hopper and the itemstack is a ruleblock. This should stop rule block transfer via hoppers.

Same should probably be done with droppers.
