### ISSUE TITLE
Item Exchange - Shops are not working

### ISSUE THREAD

**Issue by oranger68** [gmlaxfanatic/ItemExchange#54]
I am not able to use item exchange to buy or sell anything.  When I hit the chests with an open hand the Item Exchange does not show me what options are available.  I also tried to increment the items with lore to see if the bug has been addressed, but it seems that the shift clicking to change the amount of the item has also been disabled.

**Comment by gmlaxfanatic** [comment]
It appears things broke with the most recent update, thanks for letting us know. 

Rule saving is probably not working. /iec will create an exchange but the button lore has the word item at the beginning of it, it therefor fails to parse so no rule blocks are ever detected. Specifically the input will have item is plain white text and the output will have item in italic purple text.

**Comment by shadowjay1** [comment]
Oops.
