### ISSUE TITLE
Deal with space left in ruleblock lore when an item doesn't have enchantments

### ISSUE THREAD

**Issue by gmlaxfanatic** [gmlaxfanatic/ItemExchange#72]
Currently items without enchantments have a line of hidden lore that contains no displayed text. This likely as issue that can't be dealt with (we don't want to store the info in the displayname). However, this empty line is still present when the item displays additional data such as for lore, ideally the lore should be included in the line with the hidden data storage if the item doesn't have enchantments to eliminate the empty displayed line.

**Comment by shadowjay1** [comment]
I think this was a bonus fix in e578809223ffe178fff54534b55f62729a271ee9.
