### ISSUE TITLE
Ability to sell players pearls.

### ISSUE THREAD

**Issue by killyourfacego** [gmlaxfanatic/ItemExchange#77]
I brought in a couple of friends to civtest.  Pearled them and attempted to create output rule blocks for their specific ender pearls.  The exchanges simply did not recognize their pearls as being enough of the expected output to make an exchange.

**Comment by killyourfacego** [comment]
My apologies.  Disregard this issue.  I just retested it and was able to successfully purchase a specific pearled player's ender pearl.

**Comment by gmlaxfanatic** [comment]
awesome thank for the feedback
