### ISSUE TITLE
Throw an event when an exchange occurs

### ISSUE THREAD

**Issue by gmlaxfanatic** [gmlaxfanatic/ItemExchange#8]
This will allow recording via jukealerts

**Comment by gmlaxfanatic** [comment]
Probably pass a player, location, input and output itemStack

**Comment by shadowjay1** [comment]
Oops, didn't see that comment. An input and output itemstack shouldn't be too hard to add.

**Comment by gmlaxfanatic** [comment]
Fixed in  a36863d
