### ISSUE TITLE
Issue with security notes

### ISSUE THREAD

**Issue by oranger68** [gmlaxfanatic/ItemExchange#80]
I know that this is kind of an ongoing issue, but all the other tickets have been closed.  I am able to create a rule set for the security notes.  However, I am unable to use them as currency to buy from chests.  The lore on the rule set also changes when you try to change the value.  It is not the same problem where the "&&r" is added during every change.  It looks like a "2" is being added to the front of the second line of lore and the text changes color.  The "2" doesn't add on after every change like the "&&r" did.

**Comment by gmlaxfanatic** [comment]
Ongoing reporting is great. The issues get closed when ShadowJay thinks he has solved them, I then get the code onto CivTest in the next 24/48 hours and rely on reports like this to see if it works. Sounds like we're getting close to the lore working but not there yet...

**Comment by shadowjay1** [comment]
Can you provide some screenshots?

**Comment by gmlaxfanatic** [comment]
Looks like this is fixed and security notes work now!
