### ISSUE TITLE
Itemexchange makes pay-to-use redstone machines impossible

### ISSUE THREAD

**Issue by Xirtan** [gmlaxfanatic/ItemExchange#89]
With physical shop, one could create shops which only accepted payment and did not give outputs (i.e. buy 0 for 1i). Using the redstone output capabilities of a hopper, this could be used to create redstone machines which were activated by payment. Itemexchange, however, requires an output to be present in order to function. This makes these sorts of machines impossible, and removes any possible contribution they could have to the in-game economy. 

The problem is easily fixed: simply allow itemexchange shops to function without an output.

**Comment by shadowjay1** [comment]
Set the output amount to 0.
