### ISSUE TITLE
Allow global reporting of exchanges which currently sell or buy an item

### ISSUE THREAD

**Issue by gmlaxfanatic** [gmlaxfanatic/ItemExchange#9]
Every time an exchange is interacted with record its input and outputs, use this to report a global tally when someone asks for it.

First needs community/ttk2 approval before it could be implemented, probably should see if people want it before putting the effort into making the database.

**Comment by shadowjay1** [comment]
I think this would be better accomplished by a bot recording JukeAlert notifications and recording them to a database.
