### ISSUE TITLE
Shiftclick problems

### ISSUE THREAD

**Issue by ttk2** [gmlaxfanatic/ItemExchange#93]
Shift-clicking does not move an input or output rule at all. Due to the inventory lag, it appears to, but quickly reappears in its original location with any rule's amounts increased by 1 (ie, an 'Input 1 diamond' rule becomes 'Input 2 diamond'). I've noticed it when shift-clicking rules from my inventory to my hotbar, from inventory to chest, and from chest to inventory, so it is likely that any and all shift-clicking will show the incrementing behavior. Bulk rules do not seem to be affected by this, but I haven't double checked.

Reported on behalf of 

http://www.reddit.com/user/HermitMabo

**Comment by gmlaxfanatic** [comment]
Opposite the normal minecraft fashion, this is a developed feature that once discovered seems to be declared as a bug!

Looks like its not that helpful so it should probably be removed or toggled off.

**Comment by ttk2** [comment]
What exactly are you supposed to use it for?

**Comment by gmlaxfanatic** [comment]
Easily adjusting shop prices to make minor market adjustments. So if you have a currency exchange, and the prices go up by one, you just open the chest and shift click the block. This is opposed to placing the block in your hand and typing \ies #.
