### ISSUE TITLE
/iec command IndexOutOfBoundsException

### ISSUE THREAD

**Issue by erocs** [gmlaxfanatic/ItemExchange#99]
23:16:08 [INFO] XXXXXX issued server command: /iec
23:16:08 [SEVERE] java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
23:16:08 [SEVERE]       at java.util.ArrayList.rangeCheck(ArrayList.java:604)
23:16:08 [SEVERE]       at java.util.ArrayList.get(ArrayList.java:382)
23:16:08 [SEVERE]       at com.untamedears.ItemExchange.command.commands.CreateCommand.execute(CreateCommand.java:39)
23:16:08 [SEVERE]       at com.untamedears.ItemExchange.command.CommandHandler.dispatch(CommandHandler.java:62)
23:16:08 [SEVERE]       at com.untamedears.ItemExchange.ItemExchangePlugin.onCommand(ItemExchangePlugin.java:59)
23:16:08 [SEVERE]       at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
23:16:08 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:192)
23:16:08 [SEVERE]       at org.bukkit.craftbukkit.v1_6_R3.CraftServer.dispatchCommand(CraftServer.java:527)
23:16:08 [SEVERE]       at net.minecraft.server.v1_6_R3.PlayerConnection.handleCommand(PlayerConnection.java:976)
23:16:08 [SEVERE]       at net.minecraft.server.v1_6_R3.PlayerConnection.chat(PlayerConnection.java:887)
23:16:08 [SEVERE]       at net.minecraft.server.v1_6_R3.PlayerConnection.a(PlayerConnection.java:834)
23:16:08 [SEVERE]       at net.minecraft.server.v1_6_R3.Packet3Chat.handle(SourceFile:49)
23:16:08 [SEVERE]       at org.spigotmc.netty.NettyNetworkManager.b(NettyNetworkManager.java:230)
23:16:08 [SEVERE]       at net.minecraft.server.v1_6_R3.PlayerConnection.e(PlayerConnection.java:116)
23:16:08 [SEVERE]       at net.minecraft.server.v1_6_R3.ServerConnection.b(SourceFile:37)
23:16:08 [SEVERE]       at org.spigotmc.netty.NettyServerConnection.b(NettyServerConnection.java:132)
23:16:08 [SEVERE]       at net.minecraft.server.v1_6_R3.MinecraftServer.t(MinecraftServer.java:594)
23:16:08 [SEVERE]       at net.minecraft.server.v1_6_R3.DedicatedServer.t(DedicatedServer.java:240)
23:16:08 [SEVERE]       at net.minecraft.server.v1_6_R3.MinecraftServer.s(MinecraftServer.java:483)
23:16:08 [SEVERE]       at net.minecraft.server.v1_6_R3.MinecraftServer.run(MinecraftServer.java:415)
23:16:08 [SEVERE]       at net.minecraft.server.v1_6_R3.ThreadServerApplication.run(SourceFile:583)

**Comment by ariehkovler** [comment]
Confirmed - just came to file the same issue

**Comment by erocs** [comment]
Still exists on the main server. Looks like this pull was never accepted?

**Comment by ttk2** [comment]
Fork merge recompile. I will make a fork in a few hours when I get a
chance.
